# Generated by Django 4.2.13 on 2026-06-28 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerAdvisorRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_role', models.CharField(default='Software Engineer', max_length=255)),
                ('location', models.CharField(default='United States', max_length=255)),
                ('career_paths', models.JSONField(blank=True, null=True)),
                ('salary_insights', models.JSONField(blank=True, null=True)),
                ('recommended_jobs', models.JSONField(blank=True, null=True)),
                ('action_plan', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_advice', to='resume_analyzer.resumerecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_advice', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'career_advisor_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
